export const ADD_INITIAL_SHOP_LIST = 'ADD_INITIAL_SHOP_LIST';
export const ADD_SHOP = 'ADD_SHOP';
export const SHOW_DATA_FOR_EDITING = 'SHOW_DATA_FOR_EDITING';
export const EDIT_SHOP = 'EDIT_SHOP';
export const ADD_EDIT_SHOP_ITEM = 'ADD_EDIT_SHOP_ITEM';
export const REMOVE_EDIT_SHOP_ITEM = 'REMOVE_EDIT_SHOP_ITEM';
export const REMOVE_EDITING_SHOP = 'REMOVE_EDITING_SHOP';
export const SHOP_DETAILS = 'SHOP_DETAILS';

// shop Items
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_ITEM = 'CLEAR_ITEM';

